# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:

      - name: 🦑 Left metrics
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: ryandeering
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Dublin
          filename: metrics.left.svg

          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_topics: no



      - name: 🦑 Right metrics
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: ryandeering
          template: classic
          base: ""
          config_timezone: Europe/Dublin
          filename: metrics.right.svg

          plugin_achievements: yes
          plugin_achievements_limit: 10
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          repositories_forks: yes
          plugin_traffic: yes
